server:
  port: 8086
  env: dev

database:
  host: postgres
  port: 5432
  user: postgres
  password: password
  dbname: vacancy_db
  sslmode: disable

jwt:
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQy0TSI95s6hkPCFyicGS8oVoAzB7
    yiQhjrsy9KV4QivobyYsb89YxM7BJ+HHGhL83+DcKwRViLm3SlMV6NP/IQ==
    -----END PUBLIC KEY-----